parameters:
  data-provider.movies: tmdb
  data-provider.shows: tvdb
  tmdb.api-token: ""
  tmdb.movies.language: en-US
  tmdb.shows.language: en-US
  tvdb.api-key: ""
  tvdb.movies.language: eng
  tvdb.shows.language: eng
  scrobbler.use-queue: false
  show-fetch-interval: 86400
  image-fetcher.storage-path: "%kernel.cache_dir%/images"
  image-fetcher.download-all-on-update: true
  user.enable-register: true
  history.items-per-page: 100
  history.max-previous-next-pages: 3
  shows.max-episodes: 10
  overview.max-episodes: 5
  overview.max-movies: 5
  overview.max-next-episode-shows: 5
  now-watching.storage-path: "%kernel.cache_dir%/now-watching"
  now-watching.max-age: 300
